# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b74fceb4ebec563e678a964d28ea740c35e7b47a483ad204e1874ac57d8c61f23acabff90dbcfa2afb4db6681facac8a498c3ec73c032efb1a9d6ababbb5c0

test:
  secret_key_base: 7690e35942fa3cf690ac96d25bf562e19cffc8a7a74a8a8a2254976a1068932e8fbc7d5471180ec7ad07beeb03d0afa03cf1566161631f68d550a24a62ab4954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
